# fly.toml file generated for diamond-hands on 2022-12-21T16:15:21-05:00

app = "diamond-hands"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  TOKEN_SECRET = "merryxmas"
  MONGODB_URI = "mongodb+srv://marco_server:marco_server@atlascluster.rb2mf0q.mongodb.net/finalProject-diamond-hands-database"
  API_KEY = "API_KEY42ABLOH2VN4148335QUZBTF8ATRYT5AM"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
